app/products/models.py
from app import db
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import String, Integer, Float, ForeignKey, Boolean


class Category(db.Model):
    __tablename__ = "categories"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    name: Mapped[str] = mapped_column(String(100), nullable=False, unique=True)

    products: Mapped[list["Product"]] = relationship("Product", back_populates="category")

    def __repr__(self):
        return f"<Category {self.name}>"


class Product(db.Model):
    __tablename__ = 'products'

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    name: Mapped[str] = mapped_column(String(100), nullable=False)
    price: Mapped[float] = mapped_column(Float, nullable=False)
    description: Mapped[str] = mapped_column(String(500), nullable=True)

    # Нове поле (Частина 4)
    active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)

    category_id: Mapped[int | None] = mapped_column(ForeignKey('categories.id'), nullable=True)
    category: Mapped["Category"] = relationship("Category", back_populates="products")

    def __repr__(self):
        return f"<Product {self.name}>"

app/products/__init__.py
from flask import Blueprint

products_bp = Blueprint('products', __name__, template_folder='templates', url_prefix='/products')

from . import views

app/products/views.py
from flask import render_template, abort
from . import products_bp
from .models import Product
from app import db

@products_bp.route("/")
def list_products():
    products = db.session.query(Product).all()
    return render_template("products/list.html", products=products)

@products_bp.route("/<int:product_id>")
def product_detail(product_id):
    product = db.session.get(Product, product_id)
    if not product:
        abort(404)
    return render_template("products/detail.html", product=product, product_id=product_id)

app/products/templates/products/detail.html
{% extends "base.html" %}

{% block content %}
<h2>Деталі товару</h2>
<p>Ви переглядаєте товар з ID: {{ product_id }}</p>
<a href="{{ url_for('products.list_products') }}">Повернутися до списку</a>
{% endblock %}

app/products/templates/products/list.html
{% extends "base.html" %}

{% block content %}
<h2>Список товарів</h2>
<ul>
{% for product in products %}
    <li>
        <a href="{{ url_for('products.product_detail', product_id=product.id) }}">{{ product.name }}</a>
    </li>
{% endfor %}
</ul>
{% endblock %}